---
abstract: 'manage your http load balancer in seconds'
author:
  - 'shelling <navyblueshellingford@gmail.com>'
  - 'shelling <navyblueshellingford@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Balancer
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Modern::Perl: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Singleton: 0
  MooseX::Storage: 0
  Namespace::Dispatch: 0.07
  Path::Tiny: 0
  Text::Table: 0
  Text::Xslate: 0
  YAML::Any: 0
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.0.1
